/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RPeXwu1z3cd
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import React from "react";
import Location from "../about-us/location";
import Image from "next/image";

export function AboutUs() {
  return (
    <>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Established 2015
                </div>
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                  KEE RESTAURANT
                </h1>
                <p className="max-w-[600px] text-white bg-[rgba(0,0,0,0.5)] p-2 rounded-xl md:text-xl dark:text-gray-400">
                  Serving up delicious, locally-sourced cuisine in the heart of
                  the city. Experience the flavors of our community.
                </p>
              </div>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                <Link
                  className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  href="/menu"
                >
                  View Menu
                </Link>
                <Link
                  className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50  dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                  href="/reservation"
                >
                  Make a reservation
                </Link>
              </div>
            </div>

            <Image
              alt="The Rustic Spoon"
              className=" object-cover z-[-1] bg-center"
              fill
              src="https://firebasestorage.googleapis.com/v0/b/kee-restaurant.appspot.com/o/AdobeStock_761945624_Preview_Editorial_Use_Only.jpeg?alt=media&token=43b5aa64-8d69-4dc3-ae25-a48fbf900827"
            />
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
            <div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                Find Us
              </h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed dark:text-gray-400">
                Visit us at our cozy location in the heart of the city, just a
                short walk from the metro station.
              </p>
              {/* <Image
                alt="Kitchen"
                className="rounded-lg object-cover"
                height="600"
                src={"/location.jpg"}
                style={{
                  aspectRatio: "800/600",
                  objectFit: "cover",
                }}
                width="800"
              /> */}
            </div>
            <div className="rounded-lg overflow-hidden" />
          </div>
          <Location />
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                Partnerships
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                Collaborating with the Best
              </h2>
              <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                We're proud to partner with local businesses to bring you the
                finest ingredients and products.
              </p>
            </div>
          </div>
          <div className="mx-auto grid items-center gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
            <div className="grid gap-1">
              <img
                alt="Coffee Partner"
                className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                height="70"
                src="/placeholder.svg"
                width="140"
              />
              <h3 className="text-lg font-bold">Artisan Coffee</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Locally roasted coffee beans for the perfect cup.
              </p>
            </div>
            <div className="grid gap-1">
              <img
                alt="Snack Partner"
                className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                height="70"
                src="/placeholder.svg"
                width="140"
              />
              <h3 className="text-lg font-bold">Gourmet Snacks</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Handcrafted snacks to complement your meal.
              </p>
            </div>
            <div className="grid gap-1">
              <img
                alt="Bakery Partner"
                className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                height="70"
                src="/placeholder.svg"
                width="140"
              />
              <h3 className="text-lg font-bold">Artisanal Bakery</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Fresh-baked breads and pastries daily.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
            <div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                Our Restaurant
              </h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed dark:text-gray-400">
                Step inside our cozy and inviting restaurant, where you'll find
                a warm and welcoming atmosphere. Our kitchen is open for all to
                see, allowing you to watch our talented chefs at work as they
                prepare each dish with care and attention to detail.
              </p>
            </div>
            <div className="grid gap-4">
              <Image
                alt="Kitchen"
                className="rounded-lg object-cover"
                height="600"
                src="https://firebasestorage.googleapis.com/v0/b/kee-restaurant.appspot.com/o/AdobeStock_218767403_Preview.jpeg?alt=media&token=5b762787-86ec-463e-9625-df79faaf60aa"
                style={{
                  aspectRatio: "800/600",
                  objectFit: "cover",
                }}
                width="800"
              />
              <Image
                alt="Tables"
                className="rounded-lg object-cover"
                height="600"
                src="https://firebasestorage.googleapis.com/v0/b/kee-restaurant.appspot.com/o/AdobeStock_466427886_Preview.jpeg?alt=media&token=9b8c8815-ba71-4a10-8654-5fe862bcfe5a"
                style={{
                  aspectRatio: "800/600",
                  objectFit: "cover",
                }}
                width="800"
              />
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
            <div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                Our Parking
              </h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed dark:text-gray-400">
                We have a spacious parking lot located just a short walk from
                the restaurant, making it easy for you to visit us. Our lot is
                well-lit and secure, ensuring a safe and convenient experience
                for all our guests.
              </p>
            </div>
            <div className="rounded-lg overflow-hidden">
              <Image
                alt="Parking Lot"
                className="rounded-lg object-cover"
                height="600"
                src="https://firebasestorage.googleapis.com/v0/b/kee-restaurant.appspot.com/o/AdobeStock_529868714_Preview.jpeg?alt=media&token=8748b927-8d20-49c5-8a2b-e821ba63daa9"
                style={{
                  aspectRatio: "800/600",
                  objectFit: "cover",
                }}
                width="800"
              />
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
