/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/GbMLdGQksTe
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

export function FeedBack() {
  return (
    <div className="mx-auto max-w-2xl space-y-6 px-4 py-12 md:px-6 lg:px-8">
      <div className="space-y-2 text-center">
        <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
          Give Us Your Feedback
        </h2>
        <p className="text-gray-500 dark:text-gray-400">
          Please rate your experience and share any complaints or feedback.
        </p>
      </div>
      <div className="space-y-6">
        <div className="flex items-center justify-center gap-2">
          <StarIcon className="h-8 w-8 fill-gray-900 dark:fill-gray-50" />
          <StarIcon className="h-8 w-8 fill-gray-900 dark:fill-gray-50" />
          <StarIcon className="h-8 w-8 fill-gray-900 dark:fill-gray-50" />
          <StarIcon className="h-8 w-8 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
          <StarIcon className="h-8 w-8 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
          <span className="text-2xl font-medium">3.5</span>
        </div>
        <form className="grid gap-4">
          {/* <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="name">Name</Label>
              <Input id="name" placeholder="Enter your name" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" placeholder="Enter your email" type="email" />
            </div>
          </div> */}
          <div className="space-y-2">
            <Label htmlFor="feedback">Send us feedback anonymously</Label>
            <Textarea
              className="min-h-[150px]"
              id="feedback"
              placeholder="help us by sharing your feedback or complaints"
            />
          </div>
          <Button type="submit">Submit Feedback</Button>
        </form>
      </div>
    </div>
  );
}

function StarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}
