"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LiSF4PBPytK
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import Link from "next/link";
import {
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenu,
} from "@/components/ui/navigation-menu";
import { CardContent, Card } from "@/components/ui/card";

export function Menu() {
  return (
    <main className="flex flex-col">
      <section className="bg-[#f8f8f8] py-20 px-4 md:px-6">
        <div className="container mx-auto flex flex-col items-center gap-6 md:flex-row md:justify-between">
          <div className="text-center md:text-left">
            <img
              alt="Restaurant Logo"
              className="mx-auto md:mx-0"
              height={80}
              src="/placeholder.svg"
              style={{
                aspectRatio: "80/80",
                objectFit: "cover",
              }}
              width={80}
            />
            <h1 className="text-3xl font-bold tracking-tight md:text-4xl">
              Delicious Bites
            </h1>
            <p className="text-black">
              Savor the flavors of our expertly crafted menu.
            </p>
          </div>
          <Button>Order Online</Button>
        </div>
      </section>
      <nav className="bg-white shadow-sm dark:bg-gray-950">
        <div className="container mx-auto flex justify-center py-4 px-4 md:px-6">
          <NavigationMenu>
            <NavigationMenuList>
              <Link
                className="group inline-flex h-9 w-max items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50"
                href="#"
              >
                Appetizers
              </Link>

              <Link
                className="group inline-flex h-9 w-max items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50"
                href="#"
              >
                Entrees
              </Link>

              <Link
                className="group inline-flex h-9 w-max items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50"
                href="#"
              >
                Desserts
              </Link>

              <Link
                className="group inline-flex h-9 w-max items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50"
                href="#"
              >
                Drinks
              </Link>
            </NavigationMenuList>
          </NavigationMenu>
        </div>
      </nav>
      <section className="py-12 px-4 md:px-6" id="appetizers">
        <div className="container mx-auto">
          <h2 className="mb-6 text-2xl font-bold">Appetizers</h2>
          <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            <Card>
              <CardContent>
                <img
                  alt="Appetizer"
                  className="mb-4 rounded-lg object-cover"
                  height={150}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/150",
                    objectFit: "cover",
                  }}
                  width={200}
                />
                <h3 className="mb-2 text-lg font-semibold">Bruschetta</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Toasted bread topped with tomatoes, basil, and garlic.
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Cooking Time: 15 minutes
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Ingredients: Bread, tomatoes, basil, garlic, olive oil
                </p>
                <p className="mt-4 font-semibold">$8.99</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <img
                  alt="Appetizer"
                  className="mb-4 rounded-lg object-cover"
                  height={150}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/150",
                    objectFit: "cover",
                  }}
                  width={200}
                />
                <h3 className="mb-2 text-lg font-semibold">Calamari Fritti</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Crispy fried calamari with lemon and marinara sauce.
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Cooking Time: 20 minutes
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Ingredients: Calamari, flour, lemon, marinara sauce
                </p>
                <p className="mt-4 font-semibold">$12.99</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <img
                  alt="Appetizer"
                  className="mb-4 rounded-lg object-cover"
                  height={150}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/150",
                    objectFit: "cover",
                  }}
                  width={200}
                />
                <h3 className="mb-2 text-lg font-semibold">Meatballs</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Homemade meatballs in a rich tomato sauce.
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Cooking Time: 45 minutes
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Ingredients: Ground beef, breadcrumbs, parmesan, tomato sauce
                </p>
                <p className="mt-4 font-semibold">$9.99</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <img
                  alt="Appetizer"
                  className="mb-4 rounded-lg object-cover"
                  height={150}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/150",
                    objectFit: "cover",
                  }}
                  width={200}
                />
                <h3 className="mb-2 text-lg font-semibold">Caprese Salad</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Fresh mozzarella, tomatoes, and basil with balsamic glaze.
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Cooking Time: 10 minutes
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Ingredients: Mozzarella, tomatoes, basil, balsamic glaze
                </p>
                <p className="mt-4 font-semibold">$11.99</p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
      <section className="py-12 px-4 md:px-6" id="entrees">
        <div className="container mx-auto">
          <h2 className="mb-6 text-2xl font-bold">Entrees</h2>
          <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            <Card>
              <CardContent>
                <img
                  alt="Entree"
                  className="mb-4 rounded-lg object-cover"
                  height={150}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/150",
                    objectFit: "cover",
                  }}
                  width={200}
                />
                <h3 className="mb-2 text-lg font-semibold">Chicken Parmesan</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Breaded chicken breast topped with marinara and mozzarella.
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Cooking Time: 45 minutes
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Ingredients: Chicken, breadcrumbs, marinara, mozzarella
                </p>
                <p className="mt-4 font-semibold">$18.99</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <img
                  alt="Entree"
                  className="mb-4 rounded-lg object-cover"
                  height={150}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/150",
                    objectFit: "cover",
                  }}
                  width={200}
                />
                <h3 className="mb-2 text-lg font-semibold">Grilled Salmon</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Fresh salmon fillet grilled and served with lemon.
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Cooking Time: 20 minutes
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Ingredients: Salmon, lemon, olive oil
                </p>
                <p className="mt-4 font-semibold">$22.99</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <img
                  alt="Entree"
                  className="mb-4 rounded-lg object-cover"
                  height={150}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/150",
                    objectFit: "cover",
                  }}
                  width={200}
                />
                <h3 className="mb-2 text-lg font-semibold">
                  Fettuccine Alfredo
                </h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Fettuccine pasta in a creamy Parmesan sauce.
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Cooking Time: 30 minutes
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Ingredients: Fettuccine, butter, cream, parmesan
                </p>
                <p className="mt-4 font-semibold">$16.99</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <img
                  alt="Entree"
                  className="mb-4 rounded-lg object-cover"
                  height={150}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/150",
                    objectFit: "cover",
                  }}
                  width={200}
                />
                <h3 className="mb-2 text-lg font-semibold">Steak Frites</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Grilled steak served with crispy French fries.
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Cooking Time: 35 minutes
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Ingredients: Steak, potatoes, oil, salt, pepper
                </p>
                <p className="mt-4 font-semibold">$24.99</p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
      <section className="py-12 px-4 md:px-6" id="desserts">
        <div className="container mx-auto">
          <h2 className="mb-6 text-2xl font-bold">Desserts</h2>
          <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            <Card>
              <CardContent>
                <img
                  alt="Dessert"
                  className="mb-4 rounded-lg object-cover"
                  height={150}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/150",
                    objectFit: "cover",
                  }}
                  width={200}
                />
                <h3 className="mb-2 text-lg font-semibold">Tiramisu</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Classic Italian dessert with espresso-soaked ladyfingers.
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Cooking Time: 30 minutes
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
                  Ingredients: Ladyfingers, espresso, mascarpone, cocoa
                </p>
                <p className="mt-4 font-semibold">$8.99</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <img
                  alt="Dessert"
                  className="mb-4 rounded-lg object-cover"
                  height={150}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/150",
                    objectFit: "cover",
                  }}
                  width={200}
                />
                <h3 className="mb-2 text-lg font-semibold">Crème Brûlée</h3>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </main>
  );
}
