/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LiSF4PBPytK
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import Link from "next/link";
import {
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenu,
} from "@/components/ui/navigation-menu";
import { CardContent, Card } from "@/components/ui/card";
import React from "react";
import Image from "next/image";
import porkDishes from "@/lib/porkDishes";
import DishMeal from "../menu/dish";
import fishDishes from "@/lib/fishDishes";
import vegetableDishes from "@/lib/vegetableDishes";

export function Menu() {
  return (
    <main className="flex flex-col">
      {/* <section className="relative border text-white py-20 px-4 md:px-6">
        <Image
          src={
            "https://firebasestorage.googleapis.com/v0/b/kee-restaurant.appspot.com/o/pexels-enginakyurt-2673353.jpg?alt=media&token=33b07092-5d45-4fe9-bb55-d53bf177186c"
          }
          alt="meal"
          fill
          className=" object-cover z-[-1] bg-bottom"
        ></Image>
        <div className="container mx-auto flex flex-col items-center gap-6 md:flex-row md:justify-between">
          <div className=" text-center md:text-left">
            <img
              alt="Restaurant Logo"
              className="mx-auto md:mx-0"
              height={80}
              src="/placeholder.svg"
              style={{
                aspectRatio: "80/80",
                objectFit: "cover",
              }}
              width={80}
            />
            <h1 className="text-3xl font-bold tracking-tight md:text-4xl">
              Delicious Bites
            </h1>
            <p className=" text-xl">
              Savor the flavors of our expertly crafted menu.
            </p>
          </div>
          <Button>Order Online</Button>
        </div>
      </section> */}
      <nav className="bg-white shadow-sm dark:bg-gray-950 dark:text-white">
        <div className="container mx-auto flex justify-center py-4 px-4 md:px-6">
          <Link
            className="group inline-flex h-9 w-max items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50"
            href="#appetizers"
          >
            Appetizers
          </Link>

          <Link
            className="group inline-flex h-9 w-max items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50"
            href="#entrees"
          >
            Entrees
          </Link>

          <Link
            className="group inline-flex h-9 w-max items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50"
            href="#desserts"
          >
            Desserts
          </Link>

          <Link
            className="group inline-flex h-9 w-max items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-gray-100/50 data-[state=open]:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50 dark:data-[active]:bg-gray-800/50 dark:data-[state=open]:bg-gray-800/50"
            href="#drinks"
          >
            Drinks
          </Link>
        </div>
      </nav>
      <section className="py-12 px-4 md:px-6" id="appetizers">
        <div className="container mx-auto">
          <h2 className="mb-6 text-2xl font-bold">Porks</h2>
          <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            {porkDishes.map((dish, index) => (
              <DishMeal dish={dish} key={index} />
            ))}
          </div>
        </div>
      </section>
      <section className="py-12 px-4 md:px-6" id="entrees">
        <div className="container mx-auto">
          <h2 className="mb-6 text-2xl font-bold">Fishes</h2>
          <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            {fishDishes.map((dish, index) => (
              <DishMeal dish={dish} key={index} />
            ))}
          </div>
        </div>
      </section>
      <section className="py-12 px-4 md:px-6" id="desserts">
        <div className="container mx-auto">
          <h2 className="mb-6 text-2xl font-bold">Vegetables</h2>
          <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            {vegetableDishes.map((dish, index) => (
              <DishMeal dish={dish} key={index} />
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
